### ISSUE TITLE
Package xlib-d contains invalid dependency xcb-d

### ISSUE THREAD

**Issue by MaikKlein** [rtbo/xlib-d#1]
When I build with dub --versbose and xlib-d I get

```
Package xlib-d contains invalid dependency xcb-d (ci=7)
Package xlib-d contains invalid dependency xcb-d (ci=7)
Package xlib-d contains invalid dependency xcb-d (ci=7)
Package xlib-d contains invalid dependency xcb-d (ci=7)
Package xlib-d contains invalid dependency xcb-d (ci=7)
Package xlib-d contains invalid dependency xcb-d (ci=7)
Package xlib-d contains invalid dependency xcb-d (ci=7)
Package xlib-d contains invalid dependency xcb-d (ci=7)
Package xlib-d contains invalid dependency xcb-d (ci=7)
.... 
```

Could it be that I has to be  `"xcb-d": "~>2.1.0+1.11.1"` instead of `"xcb-d": "~>1.11.1"`

https://code.dlang.org/packages/xcb-d

**Comment by ParticlePeter** [comment]
Could you please upgrade your dependency on `xcb-d` to `"~>2.1.0+1.11.1"`. There is a dub issue when a project depends optionally on `xlib-d` and `xcb-d`. Please see this issue: https://github.com/dlang/dub/issues/865 for details.

**Comment by rtbo** [comment]
@ParticlePeter I did upgrade to `~>2.1.0` (see xlib-d v0.1.1)
I can't build `erupted` package, nor before neither after the change (may be because you downgraded your xcb-d requirement meanwhile). the error msg is the one I posted in dlang/dub#865.
If you say it is OK I'll close this issue.

**Comment by ParticlePeter** [comment]
Thanks for your Response to this issue. I have pushed erupted version 1.3.10 which uses xlib-d 0.1.1 and xcb-d 2.1.0, as well as vulkan-docs 1.0.18. Could you please test this version as well? On windows I was not getting any dub error message about the dependency tree any more. You might need to delete or check the entries of the dub.selections of your project.
In any case, you've done what I asked for, so from my side this issue can be closed.

**Comment by rtbo** [comment]
yes it works. I can build without trouble.
