### ISSUE TITLE
base types in X.d have the wrong size on 64-bit

### ISSUE THREAD

**Issue by huglovefan** [rtbo/xlib-d#3]
the 5 types that are defined as `uint` in `X.d` are actually `unsigned long` in the C header on my linux system:

```
% cpp -P /usr/include/X11/X.h | grep -E 'VisualID|XID|Mask|Atom|Time'                                                                    
typedef unsigned long XID;
typedef unsigned long Mask;
typedef unsigned long Atom;
typedef unsigned long VisualID;
typedef unsigned long Time;
```

`uint` has the right size for these on 32-bit but not 64-bit where `unsigned long` in C is 8 bytes instead of 4

the right D type to use for these would be `c_ulong` from the `core.stdc.config` module

**Comment by rtbo** [comment]
thanks
